import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faHouse,
  faEnvelope,
  faFile,
  faUserShield,
  faCog,
  faSignOutAlt,
  faPaperPlane,
  faFilePen,
  faEye,
  faPen,
  faXmark,
  faClock,
  faStar,
  faPlus,
  faArrowLeft,
  faUserPlus,
  faUsers,
  faGlobe,
  faUpload,
  faKey,
  faFileAlt,
  faLink,
  faImage,
  faVideo,
  faMusic,
  faTrashCan,
  faDownload,
  faLock,
  faHashtag,
  faCreditCard,
  faSpinner,
  faSave
} from '@fortawesome/free-solid-svg-icons';

const icons = {
  dashboard: faHouse,
  messages: faEnvelope,
  assets: faFile,
  trustees: faUserShield,
  settings: faCog,
  logout: faSignOutAlt,
  send: faPaperPlane,
  save: faFilePen,
  eye: faEye,
  pen: faPen,
  close: faXmark,
  clock: faClock,
  star: faStar,
  plus: faPlus,
  arrowLeft: faArrowLeft,
  userPlus: faUserPlus,
  userShield: faUserShield,
  users: faUsers,
  globe: faGlobe,
  upload: faUpload,
  key: faKey,
  fileAlt: faFileAlt,
  link: faLink,
  image: faImage,
  video: faVideo,
  music: faMusic,
  trash: faTrashCan,
  download: faDownload,
  vault: faKey,
  lock: faLock,
  instagram: faHashtag,
  creditCard: faCreditCard,
  spinner: faSpinner,
  save: faSave,
  envelope: faEnvelope  
};

export { FontAwesomeIcon, icons };
